### ISSUE TITLE
Capture doesn't work with DCMI

### ISSUE THREAD

**Issue by obscene3190** [SimpleMethod/STM32-F7-ov2640#1]
Any solutions you can suggest?

**Comment by SimpleMethod** [comment]
You need to make sure that:
Using short connection wires , less than 10 cm (3.93 inches) - This is very, very, very important!,
All wires are properly connected,
Have a high enough clock speed for the MCU,

**You can also check the new version of the library with 320x240px resolution for testing - it always works**
